# Generated by Django 4.2.2 on 2023-06-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItaCar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='conta',
        ),
        migrations.DeleteModel(
            name='contaComum',
        ),
        migrations.DeleteModel(
            name='movimento',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
    ]
